package org.example;

import java.util.Random;

/**
 * @author Josh Archer
 * @version This class represents a Die of n sides of values stored in an array. It has a roll() function
 * that generates the values of the sides given the number of sides and a rollHistory method that stores
 * the values generated by the roll() method as values of the sides.
 */
public class Dice {
    private Random random;
    private int sides;
    private String color;

    /**
     * Parameterized constructor
     *
     * @param sides number of sides
     * @param color color of dice
     */
    public Dice(int sides, String color) {
        this.sides = sides;
        this.color = color;
        random = new Random();
    }

    /**
     * @return the number of sides of dice
     */
    public int getSides() {
        return sides;
    }

    /**
     * @return returns the color of the dice
     */
    public String getColor() {
        return color;
    }

    /**
     * @return returns the random number generated between 1 to no. of sides
     */
    public int roll() {
        return random.nextInt(sides) + 1;
    }

    /**
     * @param times the number of times to roll the dice which is the
     *              length of the rollsHistory array
     * @return returns the rollHistory array with randomly generated values
     */
    public int[] rollMany(int times) {

        if (times < 0) {
            throw new NegativeArraySizeException("negative length");
        }

        int[] rollsHistory = new int[times];
        for (int i = 0; i < times; i++) {
            rollsHistory[i] = roll();
        }
        return rollsHistory;
    }

    /**
     * @return returns a string representation of the Dice class
     */
    @Override
    public String toString() {
        return "A " + sides + " sided die";
    }
}